version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.20.4'
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
    executor:
      name: node/default
workflows:
    build-and-test:
      jobs:
        - build-and-test
