const HOUSE_DEF = {
  id: 'GEN#17#13#1',
  type: 1001,
  sub_type: 13,
  descrizione: 'root',
  sched_status: '0',
  sched_lock: '1970-01-01 01:00:00',
  status: '0',
  powerst: '0',
  schedZoneStatus: [0, 0, 0],
  elements: [
    {
      id: 'GEN#PL#3',
      data: {
        id: 'GEN#PL#3',
        type: 1001,
        sub_type: 13,
        descrizione: 'Casa ',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '0',
        powerst: '0',
        schedZoneStatus: [0, 0, 0],
        elements: [
          {
            id: 'GEN#PL#255',
            data: {
              id: 'GEN#PL#255',
              type: 1001,
              sub_type: 13,
              descrizione: 'Piano PT',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '0',
              schedZoneStatus: [0, 0, 0],
              elements: [
                {
                  id: 'GEN#PL#254',
                  data: {
                    id: 'GEN#PL#254',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Ingresso',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '0',
                    elements: [
                      {
                        id: 'DOM#LT#4.1',
                        data: {
                          id: 'DOM#LT#4.1',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce esterna',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '1',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.1',
                          placeId: 'GEN#PL#254',
                        },
                      },
                      {
                        id: 'DOM#LT#34.5',
                        data: {
                          id: 'DOM#LT#34.5',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce caldaia',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '34',
                          num_uscita: '5',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#34.5',
                          placeId: 'GEN#PL#254',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#256',
                  data: {
                    id: 'GEN#PL#256',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Cantina ',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '1',
                    elements: [
                      {
                        id: 'DOM#LT#4.2',
                        data: {
                          id: 'DOM#LT#4.2',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce cantina',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '2',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.2',
                          placeId: 'GEN#PL#256',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#269',
                  data: {
                    id: 'GEN#PL#269',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Scala ',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '2',
                    elements: [
                      {
                        id: 'DOM#LT#4.3',
                        data: {
                          id: 'DOM#LT#4.3',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce scala',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '3',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.3',
                          placeId: 'GEN#PL#269',
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
          {
            id: 'GEN#PL#257',
            data: {
              id: 'GEN#PL#257',
              type: 1001,
              sub_type: 13,
              descrizione: 'Piano 1',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '0',
              schedZoneStatus: [0, 0, 0],
              elements: [
                {
                  id: 'GEN#PL#258',
                  data: {
                    id: 'GEN#PL#258',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Sala da pranzo',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '3',
                    elements: [
                      {
                        id: 'DOM#LT#4.4',
                        data: {
                          id: 'DOM#LT#4.4',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Applique sala da pranzo',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '4',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.4',
                          placeId: 'GEN#PL#258',
                        },
                      },
                      {
                        id: 'DOM#LT#5.3',
                        data: {
                          id: 'DOM#LT#5.3',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce sala da pranzo',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '3',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.3',
                          placeId: 'GEN#PL#258',
                        },
                      },
                      {
                        id: 'DOM#BL#19.1',
                        data: {
                          id: 'DOM#BL#19.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella destra',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '19',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#19.1',
                          placeId: 'GEN#PL#258',
                        },
                      },
                      {
                        id: 'DOM#BL#20.1',
                        data: {
                          id: 'DOM#BL#20.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella sinistra',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '20',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#20.1',
                          placeId: 'GEN#PL#258',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#259',
                  data: {
                    id: 'GEN#PL#259',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Soggiorno',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '4',
                    elements: [
                      {
                        id: 'DOM#LT#4.6',
                        data: {
                          id: 'DOM#LT#4.6',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Faretti soggiorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '6',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.6',
                          placeId: 'GEN#PL#259',
                        },
                      },
                      {
                        id: 'DOM#LT#4.8',
                        data: {
                          id: 'DOM#LT#4.8',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Applique soggiorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '8',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.8',
                          placeId: 'GEN#PL#259',
                        },
                      },
                      {
                        id: 'DOM#LT#4.5',
                        data: {
                          id: 'DOM#LT#4.5',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Led soggiorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '5',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.5',
                          placeId: 'GEN#PL#259',
                        },
                      },
                      {
                        id: 'DOM#LT#4.7',
                        data: {
                          id: 'DOM#LT#4.7',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce della nonna',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '4',
                          num_uscita: '7',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#4.7',
                          placeId: 'GEN#PL#259',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#260',
                  data: {
                    id: 'GEN#PL#260',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Cucina ',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '5',
                    elements: [
                      {
                        id: 'DOM#LT#5.1',
                        data: {
                          id: 'DOM#LT#5.1',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce cucina',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '1',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.1',
                          placeId: 'GEN#PL#260',
                        },
                      },
                      {
                        id: 'DOM#BL#21.1',
                        data: {
                          id: 'DOM#BL#21.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella cucina',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '21',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#21.1',
                          placeId: 'GEN#PL#260',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#261',
                  data: {
                    id: 'GEN#PL#261',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Ripostiglio ',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '6',
                    elements: [
                      {
                        id: 'DOM#LT#5.5',
                        data: {
                          id: 'DOM#LT#5.5',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce ripostiglio',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '5',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.5',
                          placeId: 'GEN#PL#261',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#262',
                  data: {
                    id: 'GEN#PL#262',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Antibagno',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '7',
                    elements: [
                      {
                        id: 'DOM#LT#5.4',
                        data: {
                          id: 'DOM#LT#5.4',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Faretti antibagno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '4',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.4',
                          placeId: 'GEN#PL#262',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#263',
                  data: {
                    id: 'GEN#PL#263',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Bagno zona giorno',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '8',
                    elements: [
                      {
                        id: 'DOM#LT#5.8',
                        data: {
                          id: 'DOM#LT#5.8',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Applique bagno giorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '1',
                          powerst: '1',
                          num_modulo: '5',
                          num_uscita: '8',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.8',
                          placeId: 'GEN#PL#263',
                        },
                      },
                      {
                        id: 'DOM#LT#5.7',
                        data: {
                          id: 'DOM#LT#5.7',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Specchiera bagno giorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '1',
                          powerst: '1',
                          num_modulo: '5',
                          num_uscita: '7',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.7',
                          placeId: 'GEN#PL#263',
                        },
                      },
                      {
                        id: 'DOM#BL#22.1',
                        data: {
                          id: 'DOM#BL#22.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella bagno giorno',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '22',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#22.1',
                          placeId: 'GEN#PL#263',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#264',
                  data: {
                    id: 'GEN#PL#264',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Corridoio',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '9',
                    elements: [
                      {
                        id: 'DOM#LT#5.2',
                        data: {
                          id: 'DOM#LT#5.2',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Faretti corridoio',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '2',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.2',
                          placeId: 'GEN#PL#264',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#265',
                  data: {
                    id: 'GEN#PL#265',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Bagno zona notte',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '10',
                    elements: [
                      {
                        id: 'DOM#LT#6.6',
                        data: {
                          id: 'DOM#LT#6.6',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Applique bagno notte',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '6',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.6',
                          placeId: 'GEN#PL#265',
                        },
                      },
                      {
                        id: 'DOM#LT#6.7',
                        data: {
                          id: 'DOM#LT#6.7',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Specchiera bagno notte',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '7',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.7',
                          placeId: 'GEN#PL#265',
                        },
                      },
                      {
                        id: 'DOM#BL#23.1',
                        data: {
                          id: 'DOM#BL#23.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella bagno notte',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '23',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#23.1',
                          placeId: 'GEN#PL#265',
                        },
                      },
                      {
                        id: 'DOM#LT#34.6',
                        data: {
                          id: 'DOM#LT#34.6',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Led Doccia',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '34',
                          num_uscita: '6',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#34.6',
                          placeId: 'GEN#PL#265',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#266',
                  data: {
                    id: 'GEN#PL#266',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Camera da letto',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '11',
                    elements: [
                      {
                        id: 'DOM#LT#6.1',
                        data: {
                          id: 'DOM#LT#6.1',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce camera da letto',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '1',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.1',
                          placeId: 'GEN#PL#266',
                        },
                      },
                      {
                        id: 'DOM#LT#6.3',
                        data: {
                          id: 'DOM#LT#6.3',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Piantana camera da letto',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '3',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.3',
                          placeId: 'GEN#PL#266',
                        },
                      },
                      {
                        id: 'DOM#BL#24.1',
                        data: {
                          id: 'DOM#BL#24.1',
                          type: 2,
                          sub_type: 7,
                          descrizione: 'Tapparella camera da letto',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          open_status: '1',
                          num_modulo: '24',
                          num_uscita: '1',
                          openTime: '60',
                          closeTime: '60',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#BL#24.1',
                          placeId: 'GEN#PL#266',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#267',
                  data: {
                    id: 'GEN#PL#267',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Camera Vittoria',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '12',
                    elements: [
                      {
                        id: 'DOM#LT#5.6',
                        data: {
                          id: 'DOM#LT#5.6',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce camera Vittoria',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '5',
                          num_uscita: '6',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#5.6',
                          placeId: 'GEN#PL#267',
                        },
                      },
                      {
                        id: 'DOM#LT#6.5',
                        data: {
                          id: 'DOM#LT#6.5',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Pixar',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '5',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.5',
                          placeId: 'GEN#PL#267',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#268',
                  data: {
                    id: 'GEN#PL#268',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Camera Beatrice',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '13',
                    elements: [
                      {
                        id: 'DOM#LT#6.4',
                        data: {
                          id: 'DOM#LT#6.4',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luce camera Beatrice',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '4',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.4',
                          placeId: 'GEN#PL#268',
                        },
                      },
                      {
                        id: 'DOM#LT#6.2',
                        data: {
                          id: 'DOM#LT#6.2',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Stellina',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '2',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.2',
                          placeId: 'GEN#PL#268',
                        },
                      },
                    ],
                  },
                },
                {
                  id: 'GEN#PL#312',
                  data: {
                    id: 'GEN#PL#312',
                    type: 1001,
                    sub_type: 13,
                    descrizione: 'Terrazzo',
                    sched_status: '0',
                    sched_lock: '1970-01-01 01:00:00',
                    status: '0',
                    powerst: '0',
                    schedZoneStatus: [0, 0, 0],
                    placeOrder: '14',
                    elements: [
                      {
                        id: 'DOM#LT#6.8',
                        data: {
                          id: 'DOM#LT#6.8',
                          type: 3,
                          sub_type: 1,
                          descrizione: 'Luci esterne',
                          sched_status: '0',
                          sched_lock: '1970-01-01 01:00:00',
                          status: '0',
                          powerst: '0',
                          num_modulo: '6',
                          num_uscita: '8',
                          icon_id: '0',
                          isProtected: '0',
                          objectId: 'DOM#LT#6.8',
                          placeId: 'GEN#PL#312',
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
          {
            id: 'DOM#CL#32.1',
            data: {
              id: 'DOM#CL#32.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato piano terra',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '0',
              num_modulo: 32,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '34',
              num_uscitaI: '3',
              num_moduloE: '34',
              num_uscitaE: '3',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '190',
              soglia_man_est: '240',
              soglia_man_notte_inv: '200',
              soglia_man_notte_est: '200',
              soglia_semiauto: '200',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '8',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '50',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '50',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#32.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '266',
              auto_man: '6',
              est_inv: '0',
              soglia_attiva: '240',
              semiauto_enabled: '0',
              umidita: '59',
              auto_man_umi: '6',
              deumi_umi: '0',
              soglia_attiva_umi: '50',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#31.1',
            data: {
              id: 'DOM#CL#31.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato soggiorno',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 31,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '1',
              num_moduloE: '7',
              num_uscitaE: '1',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '215',
              soglia_man_est: '265',
              soglia_man_notte_inv: '200',
              soglia_man_notte_est: '200',
              soglia_semiauto: '220',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '1',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '50',
              soglia_man_notte_umi: '50',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '50',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#31.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '250',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '0',
              dir_out_est: '0',
              semiauto_enabled: '0',
              umidita: '47',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '50',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
              connectionStatus: 0,
            },
          },
          {
            id: 'DOM#CL#25.1',
            data: {
              id: 'DOM#CL#25.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato cucina',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '4',
              powerst: '1',
              num_modulo: 25,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '2',
              num_moduloE: '7',
              num_uscitaE: '2',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '215',
              soglia_man_est: '265',
              soglia_man_notte_inv: '170',
              soglia_man_notte_est: '270',
              soglia_semiauto: '220',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '2',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '55',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '55',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#25.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '252',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '15',
              dir_out_est: '20',
              semiauto_enabled: '0',
              umidita: '53',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '55',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#26.1',
            data: {
              id: 'DOM#CL#26.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato bagno giorno',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 26,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '3',
              num_moduloE: '7',
              num_uscitaE: '3',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '200',
              soglia_man_est: '265',
              soglia_man_notte_inv: '200',
              soglia_man_notte_est: '200',
              soglia_semiauto: '230',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '3',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '55',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '50',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#26.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '256',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '0',
              dir_out_est: '0',
              semiauto_enabled: '0',
              umidita: '47',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '55',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#27.1',
            data: {
              id: 'DOM#CL#27.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato bagno notte',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 27,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '4',
              num_moduloE: '7',
              num_uscitaE: '4',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '200',
              soglia_man_est: '265',
              soglia_man_notte_inv: '200',
              soglia_man_notte_est: '200',
              soglia_semiauto: '240',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '4',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '55',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '55',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#27.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '255',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '0',
              dir_out_est: '0',
              semiauto_enabled: '0',
              umidita: '48',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '55',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#28.1',
            data: {
              id: 'DOM#CL#28.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato camera da letto',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 28,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '5',
              num_moduloE: '7',
              num_uscitaE: '5',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '200',
              soglia_man_est: '265',
              soglia_man_notte_inv: '170',
              soglia_man_notte_est: '270',
              soglia_semiauto: '230',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '5',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '55',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '55',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#28.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '257',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '15',
              dir_out_est: '20',
              semiauto_enabled: '0',
              umidita: '47',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '55',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#30.1',
            data: {
              id: 'DOM#CL#30.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato camera Vittoria',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 30,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '7',
              num_moduloE: '7',
              num_uscitaE: '7',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '220',
              soglia_man_est: '260',
              soglia_man_notte_inv: '170',
              soglia_man_notte_est: '270',
              soglia_semiauto: '230',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '7',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '50',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '50',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#30.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '260',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '260',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '15',
              dir_out_est: '20',
              semiauto_enabled: '0',
              umidita: '39',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '50',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
          {
            id: 'DOM#CL#29.1',
            data: {
              id: 'DOM#CL#29.1',
              type: 9,
              sub_type: 16,
              descrizione: 'Termostato camera Beatrice',
              sched_status: '0',
              sched_lock: '1970-01-01 01:00:00',
              status: '0',
              powerst: '1',
              num_modulo: 29,
              num_ingresso: 1,
              num_moduloIE: '0',
              num_uscitaIE: '0',
              num_moduloI: '7',
              num_uscitaI: '6',
              num_moduloE: '7',
              num_uscitaE: '6',
              num_moduloI_ana: '0',
              num_uscitaI_ana: '0',
              num_moduloE_ana: '0',
              num_uscitaE_ana: '0',
              soglia_man_inv: '215',
              soglia_man_est: '265',
              soglia_man_notte_inv: '170',
              soglia_man_notte_est: '270',
              soglia_semiauto: '230',
              night_mode: '0',
              soglia_auto_inv: '200',
              soglia_auto_est: '200',
              out_enable_inv: '0',
              out_enable_est: '0',
              dir_enable_inv: '0',
              dir_enable_est: '0',
              heatAutoFanDisable: '0',
              coolAutoFanDisable: '0',
              heatSwingDisable: '0',
              coolSwingDisable: '0',
              out_type_inv: '0',
              out_type_est: '0',
              temp_base_inv: '200',
              temp_base_est: '200',
              num_moduloUD: '0',
              num_uscitaUD: '0',
              num_moduloU: '0',
              num_uscitaU: '0',
              num_moduloD: '33',
              num_uscitaD: '6',
              num_moduloU_ana: '0',
              num_uscitaU_ana: '0',
              num_moduloD_ana: '0',
              num_uscitaD_ana: '0',
              out_enable_umi: '0',
              out_enable_deumi: '0',
              dir_enable_umi: '0',
              dir_enable_deumi: '0',
              humAutoFanDisable: '0',
              dehumAutoFanDisable: '0',
              humSwingDisable: '0',
              dehumSwingDisable: '0',
              out_type_umi: '0',
              out_type_deumi: '0',
              soglia_man_umi: '50',
              soglia_man_deumi: '64',
              soglia_man_notte_umi: '70',
              soglia_man_notte_deumi: '50',
              night_mode_umi: '0',
              soglia_semiauto_umi: '55',
              umi_base_umi: '0',
              umi_base_deumi: '0',
              coolLimitMax: '300',
              coolLimitMin: '50',
              heatLimitMax: '300',
              heatLimitMin: '50',
              icon_id: '0',
              objectId: 'DOM#CL#29.1',
              placeId: 'GEN#PL#3',
              viewOnly: '0',
              temperatura: '262',
              auto_man: '2',
              est_inv: '0',
              soglia_attiva: '265',
              out_value_inv: '0',
              out_value_est: '0',
              dir_out_inv: '15',
              dir_out_est: '20',
              semiauto_enabled: '0',
              umidita: '49',
              auto_man_umi: '2',
              deumi_umi: '0',
              soglia_attiva_umi: '64',
              out_value_umi: '0',
              out_value_deumi: '0',
              dir_out_umi: '0',
              dir_out_deumi: '0',
              semiauto_umi_enabled: '0',
            },
          },
        ],
      },
    },
    {
      id: 'DOM#CN#2.1',
      data: {
        id: 'DOM#CN#2.1',
        type: 11,
        sub_type: 15,
        descrizione: 'Controllo carichi TA ',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '255',
        powerst: '255',
        num_modulo: '2',
        num_uscita: '1',
        label_value: 'Wh',
        label_price: '€',
        thr_tab: ['-1.000000', '-1.000000', '-1.000000', '-1.000000'],
        price_thr_tab: ['-1.000000', '-1.000000', '-1.000000', '-1.000000'],
        prod: '0',
        count_div: '0.000000',
        cost: '0.180000',
        kCO2: '0.531000',
        compare: '0',
        groupOrder: '0',
        icon_id: '0',
        objectId: 'DOM#CN#2.1',
        placeId: '',
        toolbar_active: '0',
        visible: '1',
        instant_power: '1848.000000',
      },
    },
    {
      id: 'DOM#LC#2.1',
      data: {
        id: 'DOM#LC#2.1',
        type: 10,
        sub_type: 0,
        descrizione: 'Condizionatore',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '1',
        powerst: '1',
        num_modulo: 2,
        num_uscita: 1,
        icon_id: '0',
        objectId: 'DOM#LC#2.1',
        placeId: '',
        toolbar_active: '0',
        instant_power: '1848',
        num_module_TA: 34,
        num_out_TA: 8,
        description_TA: 'Controllo carichi TA ',
        out_power: 60,
      },
    },
    {
      id: 'DOM#LC#2.2',
      data: {
        id: 'DOM#LC#2.2',
        type: 10,
        sub_type: 0,
        descrizione: 'Lavastoviglie',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '1',
        powerst: '1',
        num_modulo: 2,
        num_uscita: 2,
        icon_id: '0',
        objectId: 'DOM#LC#2.2',
        placeId: '',
        toolbar_active: '0',
        instant_power: '0',
        num_module_TA: 3,
        num_out_TA: 3,
        description_TA: 'Controllo carichi TA ',
        out_power: 36,
      },
    },
    {
      id: 'DOM#LC#2.3',
      data: {
        id: 'DOM#LC#2.3',
        type: 10,
        sub_type: 0,
        descrizione: 'Lavatrice',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '1',
        powerst: '1',
        num_modulo: 2,
        num_uscita: 3,
        icon_id: '0',
        objectId: 'DOM#LC#2.3',
        placeId: '',
        toolbar_active: '0',
        instant_power: '0',
        num_module_TA: 3,
        num_out_TA: 2,
        description_TA: 'Controllo carichi TA ',
        out_power: 36,
      },
    },
    {
      id: 'DOM#LC#2.4',
      data: {
        id: 'DOM#LC#2.4',
        type: 10,
        sub_type: 0,
        descrizione: 'Forno',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '1',
        powerst: '1',
        num_modulo: 2,
        num_uscita: 4,
        icon_id: '0',
        objectId: 'DOM#LC#2.4',
        placeId: '',
        toolbar_active: '0',
        instant_power: '0',
        num_module_TA: 3,
        num_out_TA: 1,
        description_TA: 'Controllo carichi TA ',
        out_power: 46,
      },
    },
    {
      id: 'DOM#LC#2.5',
      data: {
        id: 'DOM#LC#2.5',
        type: 10,
        sub_type: 0,
        descrizione: 'Induzione',
        sched_status: '0',
        sched_lock: '1970-01-01 01:00:00',
        status: '1',
        powerst: '1',
        num_modulo: 2,
        num_uscita: 5,
        icon_id: '0',
        objectId: 'DOM#LC#2.5',
        placeId: '',
        toolbar_active: '0',
        instant_power: '0',
        num_module_TA: 3,
        num_out_TA: 4,
        description_TA: 'Controllo carichi TA ',
        out_power: 69,
      },
    },
  ],
};
